### ISSUE TITLE
[Windows] AttributeError: modue 'signal' has no attribute 'SIGHUP'

### ISSUE THREAD

**Issue by Dhs92** [leoboiko/myougiden#6]
[Getting this error after successfully installing on Windows 10](http://i.imgur.com/4esjiDm.png)

**Comment by leoboiko** [comment]
Hm; this project is on hiatus, but I never meant for it to run on Windows, or tried to.  Apparently Windows doesn't have SIGHUP, so it has to be behind a conditional: https://github.com/Kozea/Radicale/commit/ea97c014b7e03d8cb2dd094f7f800f68e2ee4133

I'll try to fix this, but I can't promise it will run on Windows even then. Thanks for the bug report!
